Add i18n workflow and script

diff --git a/.github/workflows/update_k8s_deployment.yaml b/.github/workflows/update_k8s_deployment.yaml
--- a/.github/workflows/update_k8s_deployment.yaml
+++ b/.github/workflows/update_k8s_deployment.yaml
@@ -11,12 +11,85 @@ on:
   push:
     branches:
       - main
+      - feature/streamline_i18n
 
 jobs:
+  i18n:
+    runs-on: ubuntu-latest
+    environment: SplatTop
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+        with:
+          token: ${{ secrets.CI_SPLATTOP_TOKEN }}
+          fetch-depth: 0
+
+      - name: Check for i18n changes
+        id: check_i18n_changes
+        run: |
+          echo "Checking for changes in i18n/"
+          LATEST_TAG=$(git describe --tags --always `git rev-list --tags --max-count=1` 2>&1)
+          TAG_FETCH_EXIT_CODE=$?
+
+          if [ $TAG_FETCH_EXIT_CODE -ne 0 ]; then
+            echo "Failed to fetch latest tag, exit code: $TAG_FETCH_EXIT_CODE"
+            exit 0
+          fi
+
+          if [ -z "$LATEST_TAG" ]; then
+            echo "No tags found, skipping check"
+            exit 0
+          fi
+
+          echo "Latest tag: $LATEST_TAG"
+
+          I18N_CHANGES=$(git diff --name-only $LATEST_TAG HEAD -- 'i18n/*')
+
+          if [ -n "$I18N_CHANGES" ]; then
+            echo "i18n changes found, running i18n script"
+            echo "i18n_changed=true" >> $GITHUB_OUTPUT
+          else
+            echo "No i18n changes found"
+            echo "i18n_changed=false" >> $GITHUB_OUTPUT
+          fi
+
+      - name: Setup Git
+        run: |
+          git config --global user.name "GitHub Actions"
+          git config --global user.email "actions@github.com"
+
+      - name: Install Poetry
+        run: |
+          curl -sSL https://install.python-poetry.org | python3 -
+            echo "source $HOME/.poetry/env" >> $GITHUB_ENV
+
+      - name: Install script dependencies
+        if: steps.check_i18n_changes.outputs.i18n_changed == 'true'
+        run: |
+          poetry install --with scripts
+
+      - name: Run i18n script
+        if: steps.check_i18n_changes.outputs.i18n_changed == 'true'
+        env:
+          DO_SPACES_KEY: ${{ secrets.DO_SPACES_KEY }}
+          DO_SPACES_SECRET: ${{ secrets.DO_SPACES_SECRET }}
+          DO_SPACES_REGION: ${{ secrets.DO_SPACES_REGION }}
+          DO_SPACES_ENDPOINT: ${{ secrets.DO_SPACES_ENDPOINT }}
+          PYTHONPATH: ${{ github.workspace }}/scripts
+        run: python i18n.py
+
+      - name: Create commit
+        if: steps.check_i18n_changes.outputs.i18n_changed == 'true'
+        run: |
+          git add *
+          git commit -m "AUTO: Update i18n files"
+          git push origin HEAD
+
   check:
     runs-on: ubuntu-latest
     environment: SplatTop
     outputs:
+      github_actions: ${{ steps.check_ci_step.outputs.github_actions }}
       python_changed: ${{ steps.check_changes.outputs.python_changed }}
       react_changed: ${{ steps.check_changes.outputs.react_changed }}
 
@@ -26,6 +99,16 @@ jobs:
         with:
           token: ${{ secrets.CI_SPLATTOP_TOKEN }}
           fetch-depth: 0
+
+      - name: Check if push is from CI from "AUTO:..." commit message
+        id: check_ci_step
+        run: |
+          if [[ $(git log -1 --pretty=%B) =~ ^AUTO:.* ]]; then
+            echo "Triggered by Github Actions, exiting pipeline"
+            echo "github_actions=true" >> $GITHUB_OUTPUT
+          else
+            echo "github_actions=false" >> $GITHUB_OUTPUT
+          fi
 
       - name: Check for changes
         id: check_changes
@@ -71,6 +154,7 @@ jobs:
 
   build:
     needs: check
+    if: (needs.check.outputs.github_actions == 'false')
     runs-on: ubuntu-latest
     environment: SplatTop
     outputs:
@@ -162,7 +246,7 @@ jobs:
 
   update-deployment:
     needs: [check, build]
-    if: always()
+    if: github.ref == 'refs/heads/main' && (needs.check.outputs.github_actions == 'false')
     runs-on: ubuntu-latest
     environment: SplatTop
     outputs:
@@ -301,8 +385,8 @@ jobs:
 
   release:
     runs-on: ubuntu-latest
-    needs: update-deployment
-    if: success()
+    needs: [update-deployment, check]
+    if: success() && github.ref == 'refs/heads/main' && (needs.check.outputs.github_actions == 'false')
     steps:
       - name: Create release
         env:
